build:
    maturin build

fmt:
    cargo +nightly fmt

lint:
    cargo clippy --no-deps

fix:
    cargo clippy --no-deps --fix --allow-dirty
    @just fmt

example:
    cargo run --example cli -- ./tests/Issue066-Project_GP8B.dsn
